### Get all users published link
GET https://cse341-project1-bk0y.onrender.com/contacts
### get all users localhost
GET http://localhost:3000/contacts


### Get single user by ID published link
GET https://cse341-project1-bk0y.onrender.com/contacts/6338d07ec51624e0408341bd

### Get single user by ID localhost
GET http://localhost:3000/contacts/6338d07ec51624e0408341bd